# Base image
FROM nginx:1.27.1-alpine3.20

# Change user to root
USER root

# Change ownership to nginx user
RUN chown -R 101:101 /etc/nginx

# Add envsubst
RUN apk update && apk add envsubst curl

# Change user to nginx
USER nginx
