services:
  parser-postgres:
    # image: postgres:16.3-alpine3.20
    build:
      context: ${TWT_PARSER_POSTGRES_CONTEXT}
      dockerfile: ${TWT_PARSER_POSTGRES_DOCKERFILE}
    hostname: ${TWT_PARSER_POSTGRES_HOST}
    container_name: parser-postgres
    user: postgres
    entrypoint: ["${TWT_PARSER_POSTGRES_ENTRYPOINT}"]
    command: ["postgres", "--config_file=${TWT_PARSER_POSTGRES_CONFIG}"]
    expose: ["${TWT_PARSER_POSTGRES_PORT}/tcp"]
    env_file:
      - path: ${TWT_PARSER_POSTGRES_ENV}
        required: true
    volumes:
      - type: bind
        source: ${TWT_PARSER_POSTGRES_BIND_ENTRYPOINT_FOLDER_SOURCE}
        target: ${TWT_PARSER_POSTGRES_BIND_ENTRYPOINT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_POSTGRES_BIND_TEMPLATE_CONFIG_FOLDER_SOURCE}
        target: ${TWT_PARSER_POSTGRES_BIND_TEMPLATE_CONFIG_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_POSTGRES_BIND_TEMPLATE_INIT_FOLDER_SOURCE}
        target: ${TWT_PARSER_POSTGRES_BIND_TEMPLATE_INIT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_POSTGRES_BIND_SSL_CRT_FOLDER_SOURCE}
        target: ${TWT_PARSER_POSTGRES_BIND_SSL_CRT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_POSTGRES_BIND_SSL_CA_CRT_SOURCE}
        target: ${TWT_PARSER_POSTGRES_BIND_SSL_CA_CRT_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: volume
        source: parser-postgres-config
        target: ${TWT_PARSER_POSTGRES_VOLUME_CONFIG_FOLDER_TARGET}
        volume:
          nocopy: false
      - type: volume
        source: parser-postgres-init
        target: ${TWT_PARSER_POSTGRES_VOLUME_INIT_FOLDER_TARGET}
        volume:
          nocopy: false
      - type: volume
        source: parser-postgres-data
        target: ${TWT_PARSER_POSTGRES_VOLUME_STORAGE_FOLDER_TARGET}
        volume:
          nocopy: false
    healthcheck:
      test: [
          "CMD",
          "psql",
          "
          host=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_HOST}
          port=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_PORT}
          user=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_USER}
          dbname=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_DB}
          sslmode=verify-full
          sslcert=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_SSL_CRT}
          sslkey=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_SSL_KEY}
          sslrootcert=${TWT_PARSER_POSTGRES_HEALTHCHECK_POSTGRES_SSL_CA_CRT}
          ",
          "-c",
          "SELECT 'OK'",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 10s
    logging:
      driver: json-file
      options:
        labels-regex: "^.+"
    deploy:
      resources:
        limits:
          cpus: ${TWT_PARSER_POSTGRES_DEPLOY_CPUS_LIMIT}
          memory: ${TWT_PARSER_POSTGRES_DEPLOY_MEMORY_LIMIT}
        reservations:
          cpus: ${TWT_PARSER_POSTGRES_DEPLOY_CPUS_RESERVATION}
          memory: ${TWT_PARSER_POSTGRES_DEPLOY_MEMORY_RESERVATION}
    networks:
      parser-postgres-network:
        ipv4_address: ${TWT_PARSER_POSTGRES_NETWORK_IP_ADDRESS}
    pull_policy: missing
    restart: always

networks:
  parser-postgres-network:
    name: parser-postgres-network
    driver: bridge
    internal: false
    external: false
    attachable: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${TWT_PARSER_POSTGRES_NETWORK_SUBNET}
          ip_range: ${TWT_PARSER_POSTGRES_NETWORK_IP_RANGE}
          gateway: ${TWT_PARSER_POSTGRES_NETWORK_GATEWAY}

volumes:
  parser-postgres-config:
    name: parser-postgres-config
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${TWT_PARSER_POSTGRES_TMPFS_CONFIG_SIZE},\
        uid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_UID},\
        gid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_GID}\
        "

  parser-postgres-init:
    name: parser-postgres-init
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${TWT_PARSER_POSTGRES_TMPFS_INIT_SIZE},\
        uid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_UID},\
        gid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_GID}\
        "

  parser-postgres-data:
    name: parser-postgres-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${TWT_PARSER_POSTGRES_TMPFS_DATA_SIZE},\
        uid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_UID},\
        gid=${TWT_PARSER_POSTGRES_TMPFS_VOLUME_GID}\
        "
