services:
  parser-mongo:
    # image: mongo:7.0-rc-jammy
    build:
      context: ${TWT_PARSER_MONGO_CONTEXT}
      dockerfile: ${TWT_PARSER_MONGO_DOCKERFILE}
    hostname: ${TWT_PARSER_MONGO_HOST}
    container_name: parser-mongo
    user: mongodb
    entrypoint: ["${TWT_PARSER_MONGO_ENTRYPOINT_TARGET}"]
    command: ["mongod", "--config", "${TWT_PARSER_MONGO_CONFIG_TARGET}"]
    expose: ["${TWT_PARSER_MONGO_PORT}/tcp"]
    env_file:
      - path: ${TWT_PARSER_MONGO_ENV}
        required: true
    volumes:
      - type: bind
        source: ${TWT_PARSER_MONGO_ENTRYPOINT_FOLDER_SOURCE}
        target: ${TWT_PARSER_MONGO_ENTRYPOINT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_MONGO_TEMPLATE_FOLDER_SOURCE}
        target: ${TWT_PARSER_MONGO_TEMPLATE_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_MONGO_SSL_CRT_FOLDER_SOURCE}
        target: ${TWT_PARSER_MONGO_SSL_CRT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${TWT_PARSER_MONGO_SSL_CA_CRT_SOURCE}
        target: ${TWT_PARSER_MONGO_SSL_CA_CRT_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: volume
        source: parser-mongo-data
        target: ${TWT_PARSER_MONGO_STORAGE_FOLDER_TARGET}
        volume:
          nocopy: false
      - type: volume
        source: parser-mongo-config
        target: ${TWT_PARSER_MONGO_CONFIG_FOLDER_TARGET}
        volume:
          nocopy: false
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--host",
          "${TWT_PARSER_MONGO_HOST}",
          "--username",
          "${TWT_PARSER_MONGO_USERNAME}",
          "--password",
          "${TWT_PARSER_MONGO_PASSWORD}",
          "--tls",
          "--tlsCertificateKeyFile",
          "${TWT_PARSER_MONGO_SSL_CRT_KEY_TARGET}",
          "--tlsCAFile",
          "${TWT_PARSER_MONGO_SSL_CA_CRT_TARGET}",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 10s
    logging:
      driver: json-file
      options:
        labels-regex: "^.+"
    deploy:
      resources:
        limits:
          cpus: ${TWT_PARSER_MONGO_CPUS_LIMIT}
          memory: ${TWT_PARSER_MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${TWT_PARSER_MONGO_CPUS_RESERVATION}
          memory: ${TWT_PARSER_MONGO_MEMORY_RESERVATION}
    networks:
      parser-mongo-network:
        ipv4_address: ${TWT_PARSER_MONGO_IP_ADDRESS}
    pull_policy: missing
    restart: always

networks:
  parser-mongo-network:
    name: parser-mongo-network
    driver: bridge
    internal: false
    external: false
    attachable: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${TWT_PARSER_MONGO_NETWORK_SUBNET}
          ip_range: ${TWT_PARSER_MONGO_NETWORK_IP_RANGE}
          gateway: ${TWT_PARSER_MONGO_NETWORK_GATEWAY}

volumes:
  parser-mongo-data:
    name: parser-mongo-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${TWT_PARSER_MONGO_DATA_SIZE},\
        uid=${TWT_PARSER_MONGO_VOLUME_UID},\
        gid=${TWT_PARSER_MONGO_VOLUME_GID}\
        "

  parser-mongo-config:
    name: parser-mongo-config
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${TWT_PARSER_MONGO_CONFIG_SIZE},\
        uid=${TWT_PARSER_MONGO_VOLUME_UID},\
        gid=${TWT_PARSER_MONGO_VOLUME_GID}\
        "
