# Base image
FROM alpine:3.20

# Install make
RUN apk update &&                                           \
    apk add                                                 \
    --no-cache                                              \
    make=4.4.1-r2
