services:
  kafka:
    # image: apache/kafka:3.9.0
    build:
      context: ${COMMON_KAFKA_CONTEXT}
      dockerfile: ${COMMON_KAFKA_DOCKERFILE}
    hostname: ${COMMON_KAFKA_HOST}
    container_name: kafka
    user: appuser
    entrypoint: ["${COMMON_KAFKA_ENTRYPOINT_TARGET}"]
    command: ["/etc/kafka/docker/run"]
    expose: ["${COMMON_KAFKA_PORT}/tcp"]
    env_file:
      - path: ${COMMON_KAFKA_ENV}
        required: true
    volumes:
      - type: bind
        source: ${COMMON_KAFKA_ENTRYPOINT_FOLDER_SOURCE}
        target: ${COMMON_KAFKA_ENTRYPOINT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMMON_KAFKA_TEMPLATE_FOLDER_SOURCE}
        target: ${COMMON_KAFKA_TEMPLATE_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMMON_KAFKA_SSL_CRT_FOLDER_SOURCE}
        target: ${COMMON_KAFKA_SSL_CRT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: volume
        source: kafka-data
        target: ${COMMON_KAFKA_STORAGE_FOLDER_TARGET}
        volume:
          nocopy: false
    healthcheck:
      test: [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-cluster.sh
          cluster-id
          --bootstrap-server
          ${COMMON_KAFKA_HEALTHCHECK_BOOTSTRAP_SERVER}
          --config
          <(echo -e \"
          security.protocol=SASL_SSL\n
          sasl.mechanism=SCRAM-SHA-256\n
          sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
          username=\"${COMMON_KAFKA_HEALTHCHECK_CLIENT_USER}\" \
          password=\"${COMMON_KAFKA_HEALTHCHECK_CLIENT_PASS}\";\n
          ssl.keystore.location=${COMMON_KAFKA_HEALTHCHECK_KEYSTORE_PATH}\n
          ssl.keystore.password=${COMMON_KAFKA_HEALTHCHECK_KEYSTORE_PASSWORD}\n
          ssl.truststore.location=${COMMON_KAFKA_HEALTHCHECK_TRUSTSTURE_PATH}\n
          ssl.truststore.password=${COMMON_KAFKA_HEALTHCHECK_TRUSTSTORE_PASSWORD}\"
          )",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 10s
    logging:
      driver: json-file
      options:
        labels-regex: "^.+"
    deploy:
      resources:
        limits:
          cpus: ${COMMON_KAFKA_CPUS_LIMIT}
          memory: ${COMMON_KAFKA_MEMORY_LIMIT}
        reservations:
          cpus: ${COMMON_KAFKA_CPUS_RESERVATION}
          memory: ${COMMON_KAFKA_MEMORY_RESERVATION}
    networks:
      kafka-network:
        ipv4_address: ${COMMON_KAFKA_IP_ADDRESS}
    pull_policy: missing
    restart: always

networks:
  kafka-network:
    name: kafka-network
    driver: bridge
    internal: false
    external: false
    attachable: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${COMMON_KAFKA_NETWORK_SUBNET}
          ip_range: ${COMMON_KAFKA_NETWORK_IP_RANGE}
          gateway: ${COMMON_KAFKA_NETWORK_GATEWAY}

volumes:
  kafka-data:
    name: kafka-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${COMMON_KAFKA_DATA_SIZE},\
        uid=${COMMON_KAFKA_VOLUME_UID},\
        gid=${COMMON_KAFKA_VOLUME_GID}\
        "
