[ req ]
prompt                  = no
distinguished_name      = cert_distinguished_name_section
req_extensions          = cert_extension_section


[cert_distinguished_name_section]
countryName             = CO
stateOrProvinceName     = stateOrProvinceName
localityName            = localityName
organizationName        = organizationName
commonName              = mongoexpress

[cert_extension_section]
subjectAltName = @subject_alt_names

[subject_alt_names]
DNS.1 = mongoexpress
