services:
  redpanda:
    # image: redpandadata/console:v2.8.3
    build:
      context: ${COMMON_REDPANDA_CONTEXT}
      dockerfile: ${COMMON_REDPANDA_DOCKERFILE}
    hostname: ${COMMON_REDPANDA_HOST}
    container_name: redpanda
    user: redpandaconsole
    entrypoint: ["${COMMON_REDPANDA_ENTRYPOINT_TARGET}"]
    command: ["/app/console"]
    ports:
      - name: redpanda-port
        target: ${COMMON_REDPANDA_PORT}
        published: ${COMMON_REDPANDA_PUBLIC_PORT}
        host_ip: ${COMMON_REDPANDA_HOST_IP}
        protocol: tcp
        mode: host
    env_file:
      - path: ${COMMON_REDPANDA_ENV}
        required: true
    volumes:
      - type: bind
        source: ${COMMON_REDPANDA_ENTRYPOINT_FOLDER_SOURCE}
        target: ${COMMON_REDPANDA_ENTRYPOINT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMMON_REDPANDA_TEMPLATE_FOLDER_SOURCE}
        target: ${COMMON_REDPANDA_TEMPLATE_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMMON_REDPANDA_SSL_CRT_FOLDER_SOURCE}
        target: ${COMMON_REDPANDA_SSL_CRT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMMON_REDPANDA_SSL_CA_CRT_SOURCE}
        target: ${COMMON_REDPANDA_SSL_CA_CRT_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: volume
        source: redpanda-data
        target: ${COMMON_REDPANDA_STORAGE_FOLDER_TARGET}
        volume:
          nocopy: false
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--cacert",
          "${COMMON_REDPANDA_SSL_CA_CRT_TARGET}",
          "https://${COMMON_REDPANDA_HOST}:${COMMON_REDPANDA_PORT}/admin/health",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 10s
    logging:
      driver: json-file
      options:
        labels-regex: "^.+"
    deploy:
      resources:
        limits:
          cpus: ${COMMON_REDPANDA_CPUS_LIMIT}
          memory: ${COMMON_REDPANDA_MEMORY_LIMIT}
        reservations:
          cpus: ${COMMON_REDPANDA_CPUS_RESERVATION}
          memory: ${COMMON_REDPANDA_MEMORY_RESERVATION}
    networks:
      redpanda-network:
        ipv4_address: ${COMMON_REDPANDA_IP_ADDRESS}
      kafka-network:
    depends_on:
      kafka:
        restart: true
        condition: service_healthy
        required: true
    pull_policy: missing
    restart: always

networks:
  redpanda-network:
    name: redpanda-network
    driver: bridge
    internal: false
    external: false
    attachable: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${COMMON_REDPANDA_NETWORK_SUBNET}
          ip_range: ${COMMON_REDPANDA_NETWORK_IP_RANGE}
          gateway: ${COMMON_REDPANDA_NETWORK_GATEWAY}
  kafka-network:
    external: true

volumes:
  redpanda-data:
    name: redpanda-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${COMMON_REDPANDA_DATA_SIZE},\
        uid=${COMMON_REDPANDA_VOLUME_UID},\
        gid=${COMMON_REDPANDA_VOLUME_GID}\
        "
