# Base image
FROM redis/redisinsight:2.60.0

# Change user to root
USER root

# Change ownership to redisinsight user
RUN chown -R 1000:1000 /usr/src/app

# Add envsubst
RUN apk update && apk add envsubst

# Change user to node
USER node
