services:
  mongo-express:
    # image: mongo-express:1.0.2
    build:
      context: ${COMPOSE_COMMON_MONGO_EXPRESS_CONTEXT}
      dockerfile: ${COMPOSE_COMMON_MONGO_EXPRESS_DOCKERFILE}
    hostname: ${COMPOSE_COMMON_MONGO_EXPRESS_HOST}
    container_name: mongo-express
    user: node
    entrypoint: ["${COMPOSE_COMMON_MONGO_EXPRESS_ENTRYPOINT_TARGET}"]
    command: ["node", "app"]
    ports:
      - name: mongo-express-port
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_PORT}
        published: ${COMPOSE_COMMON_MONGO_EXPRESS_PUBLIC_PORT}
        host_ip: ${COMPOSE_COMMON_MONGO_EXPRESS_HOST_IP}
        protocol: tcp
        mode: host
    env_file:
      - path: ${COMPOSE_COMMON_MONGO_EXPRESS_ENV}
        required: true
    volumes:
      - type: bind
        source: ${COMPOSE_COMMON_MONGO_EXPRESS_ENTRYPOINT_FOLDER_SOURCE}
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_ENTRYPOINT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMPOSE_COMMON_MONGO_EXPRESS_TEMPLATE_FOLDER_SOURCE}
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_TEMPLATE_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMPOSE_COMMON_MONGO_EXPRESS_SSL_CRT_FOLDER_SOURCE}
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_SSL_CRT_FOLDER_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: bind
        source: ${COMPOSE_COMMON_MONGO_EXPRESS_SSL_CA_CRT_SOURCE}
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_SSL_CA_CRT_TARGET}
        read_only: true
        bind:
          propagation: rprivate
          create_host_path: true
          selinux: Z
      - type: volume
        source: mongoexpress-data
        target: ${COMPOSE_COMMON_MONGO_EXPRESS_STORAGE_FOLDER_TARGET}
        volume:
          nocopy: false
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--cacert",
          "${COMPOSE_COMMON_MONGO_EXPRESS_SSL_CA_CRT_TARGET}",
          "https://${COMPOSE_COMMON_MONGO_EXPRESS_HOST}:${COMPOSE_COMMON_MONGO_EXPRESS_PORT}/health",
        ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 10s
    logging:
      driver: json-file
      options:
        labels-regex: "^.+"
    deploy:
      resources:
        limits:
          cpus: ${COMPOSE_COMMON_MONGO_EXPRESS_CPUS_LIMIT}
          memory: ${COMPOSE_COMMON_MONGO_EXPRESS_MEMORY_LIMIT}
        reservations:
          cpus: ${COMPOSE_COMMON_MONGO_EXPRESS_CPUS_RESERVATION}
          memory: ${COMPOSE_COMMON_MONGO_EXPRESS_MEMORY_RESERVATION}
    networks:
      mongo-express-network:
        ipv4_address: ${COMPOSE_COMMON_MONGO_EXPRESS_IP_ADDRESS}
      parser-mongo-network:
    depends_on:
      parser-mongo:
        restart: true
        condition: service_healthy
        required: true
    pull_policy: missing
    restart: always

networks:
  mongo-express-network:
    name: mongo-express-network
    driver: bridge
    internal: false
    external: false
    attachable: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${COMPOSE_COMMON_MONGO_EXPRESS_NETWORK_SUBNET}
          ip_range: ${COMPOSE_COMMON_MONGO_EXPRESS_NETWORK_IP_RANGE}
          gateway: ${COMPOSE_COMMON_MONGO_EXPRESS_NETWORK_GATEWAY}
  parser-mongo-network:
    external: true

volumes:
  mongoexpress-data:
    name: mongoexpress-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "\
        size=${COMPOSE_COMMON_MONGO_EXPRESS_DATA_SIZE},\
        uid=${COMPOSE_COMMON_MONGO_EXPRESS_VOLUME_UID},\
        gid=${COMPOSE_COMMON_MONGO_EXPRESS_VOLUME_GID}\
        "
