# Predefined section (used in openssl req command).
[ req ]
prompt                  = no                                                    # Disable interactive prompts.
distinguished_name      = leaf_cert_section_distinguished_name                  # Section, where DN of CSR described (will be DN of Leaf certificate).
req_extensions          = leaf_cert_section_req_extensions                      # Section, where extensions of leaf certificate CSR described.

# Custom section, where DN of CSR described (will be DN of Leaf certificate).
[leaf_cert_section_distinguished_name]
countryName             = CO                                                    # Country name placeholder.
stateOrProvinceName     = stateOrProvinceName                                   # State/Province placeholder.
localityName            = localityName                                          # City/Locality placeholder.
organizationName        = organizationName                                      # Organization placeholder.
commonName              = mongo-express                                         # Common Name for leaf certificate.

# Custom section, where extensions of leaf certificate CSR described.
[leaf_cert_section_req_extensions]
subjectAltName          = @subject_alt_names                                    # Subject alternative names

# Custom section, where subject alternative names described.
[subject_alt_names]
DNS.1                   = mongo-express                                         # Type: DNS, Number: 1, Name: mongo-express
