[ ca ]
default_ca              = ca_section

[ ca_section ]
dir                     = $ENV::CA_DIR

database                = $dir/database/index.txt
new_certs_dir           = $dir/issued

certificate             = $dir/ca.crt
private_key             = $dir/ca.key

rand_serial             = yes
unique_subject          = no

default_days            = 3650
default_md              = default

name_opt                = ca_default
cert_opt                = ca_default

policy                  = intermediate_cert_policy_section

x509_extensions         = intermediate_cert_extension_section
copy_extensions         = copy

crl_extensions          = crl_extension_section
crlnumber               = $dir/crl/crlnumber.txt
default_crl_days        = 30

[ req ]
prompt                  = no
distinguished_name      = root_cert_distinguished_name_section
x509_extensions         = root_cert_extension_section

[ root_cert_distinguished_name_section ]
countryName             = CO
stateOrProvinceName     = stateOrProvinceName
localityName            = localityName
organizationName        = organizationName
commonName              = Root CA

[ root_cert_extension_section ]
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always, issuer
basicConstraints        = critical, CA:TRUE
keyUsage                = critical, digitalSignature, cRLSign, keyCertSign
# crlDistributionPoints   = URI:http://crl_server_url/root_crl.der

[ intermediate_cert_policy_section ]
countryName             = match
stateOrProvinceName     = match
localityName            = match
organizationName        = match
organizationalUnitName  = optional
emailAddress            = optional
commonName              = supplied

[ intermediate_cert_extension_section ]
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always, issuer
basicConstraints        = critical, CA:TRUE, pathlen:0
keyUsage                = critical, digitalSignature, cRLSign, keyCertSign
# crlDistributionPoints   = URI:http://crl_server_url/root_crl.der

[ crl_extension_section ]
authorityKeyIdentifier  = keyid:always, issuer
# crlDistributionPoints   = URI:http://crl_server_url/root_crl.der
