[ req ]                                                                         # Predefined section (used in openssl req command)
prompt                  = no                                                    # Disable interactive prompts

utf8                    = yes                                                   # All field values in config file in UTF-8
default_md              = sha256                                                # Default hash algorithm (SHA-256)

distinguished_name      = root_cert_section_distinguished_name                  # Section, where DN of CSR described (will be DN of ROOT CA)

req_extensions          = root_cert_section_req_extensions                      # Section, where extensions of ROOT CA CSR described

[ root_cert_section_distinguished_name ]                                        # Custom section, where DN of CSR described (will be DN of ROOT CA)
countryName             = CO                                                    # Country name placeholder
stateOrProvinceName     = stateOrProvinceName                                   # State/Province placeholder
localityName            = localityName                                          # City/Locality placeholder
organizationName        = organizationName                                      # Organization placeholder
commonName              = Root CA                                               # Common Name for ROOT CA

[ root_cert_section_req_extensions ]                                            # Custom section, where extensions that include in csr described
basicConstraints        = critical, CA:TRUE, pathlen:1                          # This is a CA certificate (critical)
keyUsage                = critical, cRLSign, keyCertSign                        # Permitted key usages (Can sign another certificates, can sign CRL)
subjectKeyIdentifier    = hash                                                  # Include current certificate ID
