[ ca ]                                                                          # Predefined section (used in openssl ca command)
default_ca              = ca_section                                            # Specifies that the default CA settings are defined in the [ca_section]

[ ca_section ]                                                                  # Custom section, where CA settings described
dir                     = $ENV::ROOT_CA_DIR                                     # Just variable with root directory of the CA (uses the environment variable ROOT_CA_DIR)

database                = $dir/database/index.txt                               # Path to the database file storing issued certificates
new_certs_dir           = $dir/issued                                           # Directory where newly issued certificates are saved

private_key             = $dir/current/ca.key                                   # Path to the ROOT CA’s private key for signing new cert

rand_serial             = yes                                                   # Generate random serial numbers (security best practice)
unique_subject          = yes                                                   # Prevent duplicate certificate subjects (DN)

default_days            = 3650                                                  # Default validity period (10 years)
default_md              = sha256                                                # Default hash algorithm (SHA-256)

name_opt                = ca_default                                            # Display format for names in output (default settings)
cert_opt                = ca_default                                            # Display format for certificates (default settings)

policy                  = root_cert_section_policy                              # Specifies the policy section for validating Distinguished Names (DN)

x509_extensions         = root_cert_section_extensions                          # Specifies the extensions section to include in certificates
copy_extensions         = none                                                  # NEVER copy extensions from CSRs (security critical)

[ root_cert_section_policy ]                                                    # Custom section, where for validating Distinguished Names (DN)
countryName             = supplied                                              # Country MUST be supplied in CSR of ROOT CA
stateOrProvinceName     = supplied                                              # State MUST be supplied in CSR of ROOT CA
localityName            = supplied                                              # Locality MUST be supplied in CSR of ROOT CA
organizationName        = supplied                                              # Organization MUST be supplied in CSR of ROOT CA
organizationalUnitName  = optional                                              # Organizational unit (optional)
emailAddress            = optional                                              # Email address (optional)
commonName              = supplied                                              # Common Name MUST be supplied in CSR of ROOT CA

[ root_cert_section_extensions ]                                                # Custom section, where extensions that include in certificate described
basicConstraints        = critical, CA:TRUE, pathlen:1                          # This is a CA certificate (critical)
keyUsage                = critical, cRLSign, keyCertSign                        # Permitted key usages (Can sign another certificates, can sign CRL)
authorityKeyIdentifier  = keyid:always, issuer:always                           # Include authority key ID (ID of the certificate that signed current)
subjectKeyIdentifier    = hash                                                  # Include current certificate ID
