# Kafka settings
kafka:
  # Brokers is a list of bootstrap servers with port (for example "localhost:9092")
  brokers:
    - ${_KAFKA_HOST}:${KAFKA_PORT}

  # Client ID that the Kafka client can use to identify itself against the target Kafka cluster
  clientId: console

  # TLS settings
  tls:
    # Enable tls
    enabled: true

    # Path to CA certificate
    caFilepath: ${_REDPANDA_SSL_CA_PATH}

    # Path to certificate
    certFilepath: ${_REDPANDA_SSL_CERT_PATH}

    # Path to key
    keyFilepath: ${_REDPANDA_SSL_KEY_PATH}

    # Check CA certificate of the kafka broker
    insecureSkipTlsVerify: true

# Login contains all configurations in order to protect Redpanda Console with a login screen
login:
  # Enable login screen
  enabled: false

  # JwtSecret is the secret key you must use to sign and encrypt the JSON web token used to store user sessions
  jwtSecret: "${_REDPANDA_JWT_SECRET}"

  # Secure cookies
  useSecureCookies: true

  # Chunk big cookie for several small cookies
  useCookieChunking: false

  # Plain authentication
  plain:
    # Enable plain authentication
    enabled: true

    # Credentials
    credentials:
      - username: "${_REDPANDA_USERNAME}"
        password: "${_REDPANDA_PASSWORD}"

# Server configures Redpanda Console's HTTP server that serves all resources, including the Frontend application
server:
  # Specifies the IP address on which the server listens for incoming HTTP requests.
  listenAddress: ${_REDPANDA_LISTEN_ADDRESS}

  # Defines the port for the HTTP server.
  listenPort: ${_REDPANDA_PORT}

  # Defines the port for the HTTPS server.
  httpsListenPort: ${_REDPANDA_TLS_PORT}

  # Redirect on this port when access http
  advertisedHttpsListenPort: ${_REDPANDA_ADVERTISED_PORT}

  # The time the server waits to complete ongoing requests before shutting down gracefully.
  gracefulShutdownTimeout: 30s

  # Maximum time allowed for reading a request from a client.
  readTimeout: 30s

  # Maximum time allowed for writing a response to a client.
  writeTimeout: 30s

  # Maximum idle time for connections before they are closed by the server.
  idleTimeout: 30s

  # Sets the level of compression for HTTP responses.
  compressionLevel: 4

  # TLS settings
  tls:
    # Enable tls
    enabled: true

    # Path to server certificate
    certFilepath: ${_REDPANDA_SSL_CERT_PATH}

    # Path to server key
    keyFilepath: ${_REDPANDA_SSL_KEY_PATH}

  # AllowedOrigins is a list of origins that can send requests from a browser to the Console API.
  allowedOrigins: ${_REDPANDA_ALLOWED_ORIGINGS}

# Prefix for all exported Prometheus metrics
metricsNamespace: console

# Logger settings
logger:
  # Valid values are: debug, info, warn, error, fatal
  level: info

# Analytics configures the telemetry service that sends anonymized usage statistics to Redpanda
analytics:
  # Enable analytics
  enabled: true
