[ req ]                                                                         # Predefined section (used in openssl req command)
prompt                  = no                                                    # Disable interactive prompts

utf8                    = yes                                                   # All field values in config file in UTF-8
default_md              = sha256                                                # Default hash algorithm (SHA-256)

distinguished_name      = leaf_cert_section_distinguished_name                  # Section, where DN of CSR described (will be DN of LEAF certificate)

req_extensions          = leaf_cert_section_req_extensions                      # Section, where extensions of LEAF CSR described

[leaf_cert_section_distinguished_name]                                          # Custom section, where DN of CSR described (will be DN of LEAF certificate)
countryName             = CO                                                    # Country name placeholder
stateOrProvinceName     = stateOrProvinceName                                   # State/Province placeholder
localityName            = localityName                                          # City/Locality placeholder
organizationName        = organizationName                                      # Organization placeholder
commonName              = parser-postgres                                       # Common Name for LEAF certificate

[leaf_cert_section_req_extensions]                                              # Custom section, where extensions of LEAF certificate CSR described
basicConstraints        = critical, CA:FALSE                                    # This is not a CA certificate (critical)
keyUsage                = critical, digitalSignature                            # Permitted key usages (Can sign handshake transcript during TLS 1.3 handshake)
extendedKeyUsage        = critical, serverAuth, clientAuth                      # Can be used for server auth and client auth
subjectKeyIdentifier    = hash                                                  # Include current certificate ID
subjectAltName          = @subject_alt_names                                    # Subject alternative names

[subject_alt_names]                                                             # Custom section, where subject alternative names described
DNS.1                   = parser-postgres                                       # Type: DNS, Number: 1, Name: parser-mongo
